// <auto-generated />
using final.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace final.Migrations.Report
{
    [DbContext(typeof(ReportContext))]
    [Migration("20180511012012_cidfdf")]
    partial class cidfdf
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("final.Report", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryId");

                    b.Property<int>("CustDocument");

                    b.Property<string>("CustName");

                    b.Property<string>("CustSurname");

                    b.Property<DateTime>("DateFlight");

                    b.Property<DateTime>("DateOfSale");

                    b.Property<int>("Place");

                    b.Property<int>("Price");

                    b.HasKey("id");

                    b.ToTable("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
